image: mcr.microsoft.com/powershell:centos-7

# Due to Container forcing /bin/bash moving to build.ps1
# before_script:
#   - Install-Module PSScriptAnalyzer

stages:
  - test
  - deploy

.base:
  tags:
    - docker

test:
  extends: .base
  script:
    - /bin/pwsh -File ./test.ps1

publish:
  extends: .base
  stage: deploy
  script:
    - Publish-Module -NuGetApiKey  $env:LPT_NugetKey -Path .\src\LinuxPowershellTools\
  only:
    - master

#Test stage, will remove in the future
# publishtest:
#   extends: .base
#   stage: deploy
#   script:
#     - Publish-Module -NuGetApiKey  $env:LPT_NugetKey -Path .\src\LinuxPowershellTools\
#   only:
#     - feature/cicd
