image:
  name: mcr.microsoft.com/powershell:centos-7
  entrypoint: ["/usr/bin/pwsh"]

before_script:
  - Install-Module PSScriptAnalyzer

stages:
  - test
  - deploy

.base:
  tags:
    - docker

test:
  extends: .base
  script:
    - gci -r ./src | %{ Invoke-ScriptAnalyzer $_.FullName }

publish:
  extends: .base
  stage: deploy
  script:
    - Publish-Module -NuGetApiKey  $env:LPT_NugetKey -Path .\src\LinuxPowershellTools\
  only:
    - master

#Test stage, will remove in the future
# publishtest:
#   extends: .base
#   stage: deploy
#   script:
#     - Publish-Module -NuGetApiKey  $env:LPT_NugetKey -Path .\src\LinuxPowershellTools\
#   only:
#     - feature/cicd
